config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :tasks
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "/home", to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def self.calculate_duration(task)
    counter = 0
    am = [12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    pm = [12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

    s = task.start_time.strftime "%l"
    e = task.end_time.strftime "%l"

    calculate = false

    if (task.start_time.strftime "%P") == "am" && (task.end_time.strftime "%P") == "am"
      am.each do |h|
        if h.to_i == s.to_i
          calculate = true
        end
        if calculate == true
          counter = counter + 1
        end
        if h.to_i == e.to_i
          calculate = false
        end
      end
    end

    if ((task.start_time.strftime "%l") > (task.end_time.strftime "%l")) || ((task.end_time.strftime "%l").to_i == 12)
      pm.each do |h|
        if calculate == true
          counter = counter + 1
        end
      end

      am.each do |h|
        if calculate == true
          counter = counter + 1
        end
        if h.to_i == e.to_i
          calculate = false
        end
      end
    end

    #<!-- ********************* -->
    if (task.start_time.strftime "%P") == "pm" && (task.end_time.strftime "%P") == "pm"
      pm.each do |h|
        if h.to_i == s.to_i
          calculate = true
        end
        if calculate == true
          counter = counter + 1
        end
        if h.to_i == e.to_i
          calculate = false
        end
      end
    end

    if ((task.start_time.strftime "%l") > (task.end_time.strftime "%l")) || ((task.end_time.strftime "%l").to_i == 12)
      am.each do |h|
        if calculate == true
          counter = counter + 1
        end
      end

      pm.each do |h|
        if calculate == true
          counter = counter + 1
        end
        if h.to_i == e.to_i
          calculate = false
        end
      end
    end

    #<!-- ****************** -->
    if (task.start_time.strftime "%P") == "am" && (task.end_time.strftime "%P") == "pm"
      am.each do |h|
        if h.to_i == s.to_i
          calculate = true
        end
        if calculate == true
          counter = counter + 1
        end
      end

      pm.each do |h|
        if calculate == true
          counter = counter + 1
        end
        if h.to_i == e.to_i
          calculate = false
        end
      end
    end

    if (task.start_time.strftime "%P") == "pm" && (task.end_time.strftime "%P") == "am"
      pm.each do |h|
        if h.to_i == s.to_i
          calculate = true
        end
        if calculate == true
          counter = counter + 1
        end
      end

      am.each do |h|
        if calculate == true
          counter = counter + 1
        end
        if h.to_i == e.to_i
          calculate = false
        end
      end
    end

    m1 = task.start_time.strftime "%M"
    m2 = task.end_time.strftime "%M"

    s1 = task.start_time.strftime "%S"
    s2 = task.end_time.strftime "%S"

    #  <!-- hours = e.to_i - s.to_i if e > s || e == s
    #   hours = s.to_i - e.to_i if s > e
    #   hours = "0#{counter}" if hours < 10 -->

    hours = "#{counter - 1}"
    hours = "0#{counter - 1}" if hours.to_i < 10

    minutes = m2.to_i - m1.to_i if m2 > m1 || m2 == m1
    minutes = m1.to_i - m2.to_i if m1 > m2
    minutes = "0#{minutes}" if minutes < 10

    seconds = s2.to_i - s1.to_i if s2 > s1 || s2 == s1
    seconds = s1.to_i - s2.to_i if s1 > s2
    seconds = "0#{seconds}" if seconds < 10

    total = "#{hours}:#{minutes}:#{seconds}"
    return total
  end

  def self.report(tasks)
    week = []
    week_days = 0
    sun = ""

    while week_days < 7
      if "#{Date.today.strftime("%A")}" == "Sunday"
        week.push({day: (Date.today + week_days), duration: 0})
        week_days += 1
      elsif Date.today.strftime("%A") != "Sunday"
        find = false
        counter = 0
        while find == false
          sun = Date.today - counter
          if sun.strftime("%A") == "Sunday"
            week.push({day: (sun + week_days), duration: 0})
            week_days += 1
            find = true
          end
          counter += 1
        end
      end
    end

    puts week

    week.each do |day|
      hours = 0
      minutes = 0
      seconds = 0

      tasks.each do |task|
        if task.created_at.strftime("%B %d, %Y") == day[:day].strftime("%B %d, %Y")
          seconds = seconds + (task.duration[6..7]).to_i
          minutes = minutes + (task.duration[3..4]).to_i
          hours = hours + (task.duration[0..1]).to_i

          if seconds >= 60
            rest = seconds
            seconds = seconds - 60
            rest = rest - seconds
            minutes = minutes + (rest / 60)
          end

          if minutes >= 60
            rest = minutes
            minutes = minutes - 60
            rest = rest - minutes
            hours = hours + (rest / 60)
          end

          # seconds = "0#{seconds}" if seconds.to_i < 10
          # minutes = "0#{minutes}" if minutes.to_i < 10
          # hours = "0#{hours}" if hours.to_i < 10

          day[:duration] = (hours * 60) + minutes
        end
      end
    end

    # counter = 1
    # arr = []

    # while counter <= 7
    #   tasks.each do |key, value|
    #     if (value.created_at.strftime("%B %d, %Y")) == (tasks[key + 1].created_at.strftime("%B %d, %Y"))
    #       arr.push({created_at: created_at.strftime("%A"), duration })
    #     end
    #   end
    # end

    week.map do |day|
      [
        day[:day].strftime("%A"),
        day[:duration].to_i,
      ]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :tasks, through: :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource_or_scope)
    "/home"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @projects = Project.all

    respond_to do |f|
      f.html
      f.json { render json: @projects }
    end
  end

  def show
  end

  def new
  end

  def create
    if (params["name"] != "")
      project = Project.create(name: params["name"], user_id: current_user.id)
    else
      project = Project.create(user_id: current_user.id)
    end
    render json: project
  end

  def edit
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @tasks = current_user.tasks
    @data = Task.report @tasks
  end

  def show
  end

  def new
  end

  def create
    @task = Task.create(name: params["name"], start_time: params["start_time"], end_time: params["end_time"], project_id: params["project_id"])
    duration = Task.calculate_duration(@task)
    @task.update(duration: duration)
    render json: task
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css?family=Inconsolata|PT+Sans|Raleway|ZCOOL+XiaoWei" rel="stylesheet">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Time Tracker</h1>    
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>

<div class="links">
<p><%= link_to "Report", tasks_path %></p>
<p id="logout"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
</div>

<div id="create_task">
    <form action="">
        <input type="text" name="taskName" id="taskName" placeholder="Task Name">

        <input type="text" name="projectName" id="projectName" placeholder="Project Name">

        <div id="select">
            <button id="s_e" class="select_time">Start Time - End Time</button>
            <button id="stopwatch" class="select_time">Stopwatch</button>
        </div>
        
        <div id="show_s_e">
            <input type="time" name="startTime" id="startTime">
            <input type="time" name="endTime" id="endTime">
        </div>

        <div id="show_stopwatch">
            <p id="timer">00: 00: 00</p>
        </div>

    <button id="submit">Done</button>
    </form>
</div>



    <% tasks_array = [] %>
    <% hours = 0 %>
    <% minutes = 0 %>
    <% seconds = 0  %>

    <% ordered_tasks = current_user.tasks.sort_by &:created_at %>

    <% ordered_tasks.each do |t| %>
        <% tasks_array.push(t) %>
    <% end %>

    <% tasks_array = tasks_array.reverse %>
    
    <% while tasks_array.empty? == false %>

    <% if seconds.to_i >= 60 %>
        <% rest = seconds.to_i %>
        <% seconds = seconds.to_i - 60 %>
        <% rest = rest - seconds.to_i %>
        <% minutes = minutes.to_i + (rest / 60) %>
    <% end %>

    <% if minutes.to_i >= 60 %>
        <% rest = minutes.to_i %>
        <% minutes = minutes.to_i - 60 %>
        <% rest = rest - minutes.to_i %>
        <% hours = hours.to_i + (rest / 60) %>
    <% end %>

    <% seconds = "0#{seconds}" if seconds.to_i < 10 %>
    <% minutes = "0#{minutes}" if minutes.to_i < 10 %>
    <% hours = "0#{hours}" if hours.to_i < 10 %>

   <div id="day_tasks">

    <% if (tasks_array[0].created_at.strftime "%B %d, %Y") == (Date.today.strftime "%B %d, %Y") %>
        <p class="day">Today</p>
    <% elsif (tasks_array[0].created_at.strftime "%B %d, %Y") == ((Date.today - 1).strftime "%B %d, %Y") %>
        <p class="day">Yesterday</p>
    <% else %>
        <p class="day"><%= tasks_array[0].created_at.strftime "%A, %B %d, %Y" %></p>
    <% end %>

  
        <% test = tasks_array[0] %>
        <% check = true %>
        <%= project_name = "" %>
      
      <% while check == true %>

       <% first_element = tasks_array.shift %>

        <% if (first_element.created_at.strftime "%B %d, %Y") == (test.created_at.strftime "%B %d, %Y") %>
            <% current_user.projects.each do |p| %>
                <% project_name = p.name if p.id == first_element.project_id %>
            <% end %>

            <% seconds = seconds.to_i + (first_element.duration[6..7]).to_i %>
            <% minutes = minutes.to_i + (first_element.duration[3..4]).to_i %>
            <% hours = hours.to_i + (first_element.duration[0..1]).to_i %>

            <div class="each_task">

            <div><p><%= first_element.name %></p></div>
                            
            <% if project_name == "No Project"%>
                <div><p id="no_project"><%= project_name %></p></div>
            <% else %>
                <div><p><%= project_name %></p></div>
            <% end %>

            <div><p><%= first_element.start_time.strftime "%I:%M %P" %> - <%= first_element.end_time.strftime "%I:%M %P" %> &nbsp; &nbsp; &nbsp; <%= first_element.duration %></p></div>

            </div>

            <hr>

                <% check = false if tasks_array.empty? %>    
      
        <% else %>
            <% tasks_array.unshift first_element %>
            <% check = false %>
        <% end %>

        <% end %>
           </div>
        <% end %>
<% end %>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<div class="links">
<p><%= link_to 'Back', root_path %></p>
<p id="logout"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
</div>

<div id="chart" style="width: auto; height: 600px;"></div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<%= javascript_tag do -%>
  google.charts.load('current', {'packages':['bar']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = JSON.parse('<%= @data.to_json.html_safe -%>');
    data.map(function(time) {
      hours = Math.floor(time[1] / 60);
      minutes = time[1] % 60;
      if (minutes < 10) {
        minutes = "0" + minutes;
      }
      time[1] = parseInt(`${hours}`);
      return time;
    });
    data = [['Week/Day', 'Duration']].concat(data);
    data = google.visualization.arrayToDataTable(data);
    var options = {
      chart: {
        title: 'Duration',
      }
    };
    var view = new google.visualization.DataView(data);
    var chart = new google.charts.Bar(document.getElementById('chart'));
    chart.draw(view, options);
  }
<% end -%>

    <%# .map(function(time) {
      const hours = Math.floor(time[1] / 60);
      let minutes = time[1] % 60;
      if (minutes < 10) {
        minutes = "0" + minutes;
      }
      time[2] = `${hours}:${minutes}`;
      return time;
    }); %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>